# 指定系统
SET(CMAKE_SYSTEM_NAME Linux)
# 系统架构
SET(CMAKE_SYSTEM_PROCESSOR  x86)

# 指定c/c++编译器
SET(CMAKE_C_COMPILER  gcc)
SET(CMAKE_CXX_COMPILER g++)
SET(CMAKE_RC_COMPILER windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
#-DCMAKE_TOOLCHAIN_FILE