# 指定系统
SET(CMAKE_SYSTEM_NAME Windows)
# 系统架构
SET(CMAKE_SYSTEM_PROCESSOR  x86)

# 指定c/c++编译器
SET(CMAKE_C_COMPILER  /usr/bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER /usr/bin/x86_64-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


#-DCMAKE_TOOLCHAIN_FILE